name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo  #this steps is important to amke sure the workflow has access to the repository
        uses: actions/checkout@v4

      - name: Welcome Message
        run: echo "My first Github Actions job"

      - name: List Files
        run: ls

      - name: Read File
        run: cat README.md

