name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        # - name: Install Cowsay program
        #   run: sudo apt install cowsay -y
        
        # - name: Execute Cowsay CMD
        #   run: cowsay -f dragon "Run for cover, I am a DRAGON.... RRAAWWRR" >> dragon.txt

        # - name: Test file exists
        #   run: grep -i "dragon" dragon.txt

        # - name: Read file
        #   run: cat dragon.txt

        - name: Execute Shell Script  #Commented steps are executed in Shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh  #path of script in the repo

        - name: List files
          run: ls -lart
