name: Test Repository Dispatch
on: 
  push
  workflow_dispatch
permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: actions/checkout@v3
      - name: extract
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer <YOUR-TOKEN>" \
          https://api.github.com/repos/mohanprasanth999/github-actions-examples/dispatches \
          -d '{"event_type":"test","client_payload":{"artefact": '"$(cat deployment-artefact/artefact.json)"'}}'

