name: Test Gcloud Setup
on: workflow_dispatch
permissions:
  contents: 'read'
  id-token: 'write'
jobs:  
  test-gcloud:
    runs-on: ubuntu-latest
    steps:
    - name: 'Auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: "projects/382383563440/locations/global/workloadIdentityPools/github/providers/github"
        service_account: "terraform-sa@dynamic-hub-299513.iam.gserviceaccount.com"
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
  
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
